on:
  push:
    branches: main

jobs:
  scrape-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::data.table
            any::rvest
            any::netstat
            any::RSelenium

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Scrape and Clean data
        run: Rscript -e 'source("R/scrape_data.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/cars_raw_data.rds
          git add data/cars_raw_data.csv
          git add data/cars_cleaned_data.rds
          git add data/cars_cleaned_data.csv
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"